# Generated by Django 4.2.2 on 2023-08-04 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
