# Generated by Django 4.2.2 on 2023-06-14 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=50)),
                (
                    "zip_code",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10000),
                            ecommerce.apps.users.models.MaxValueValidator(99999),
                        ]
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
