# Generated by Django 4.2.2 on 2023-08-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
